geekshop/adminapp/urls.py
from django.urls import path

import adminapp.views as adminapp
from adminapp.views import UserListView, UserCreateView, UserUpdateView, UserDeleteView
from adminapp.views import ProductCategoryListView, ProductCategoryCreateView, ProductCategoryUpdateView, ProductCategoryDeleteView
from adminapp.views import ProductListView, ProductCreateView, ProductReadView, ProductUpdateView, ProductDeleteView

app_name = 'adminapp'

urlpatterns = [
    # path('users/create/', adminapp.user_create, name='user_create'),
    path('users/create/', UserCreateView.as_view(), name='user_create'),
    # path('users/read/', adminapp.users, name='users'),
    path('users/read/', UserListView.as_view(), name='users'),
    path('users/update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    # path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('users/delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
    # path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),

    path('categories/create/', ProductCategoryCreateView.as_view(), name='category_create'),
    # path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/read/', ProductCategoryListView.as_view(), name='categories'),
    # path('categories/read/', adminapp.categories, name='categories'),
    path('categories/update/<int:pk>/', ProductCategoryUpdateView.as_view(), name='category_update'),
    # path('categories/update/<int:pk>/', adminapp.category_update, name='category_update'),
    path('categories/delete/<int:pk>/', ProductCategoryDeleteView.as_view(), name='category_delete'),
    # path('categories/delete/<int:pk>/', adminapp.category_delete, name='category_delete'),

    path('products/create/category/<int:pk>/', ProductCreateView.as_view(), name='product_create'),
    path('products/read/category/<int:pk>/', ProductListView.as_view(), name='products'),
    path('products/read/<int:pk>/', ProductReadView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    # path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    # path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    # path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    # path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    # path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),
]

geekshop/authapp/urls.py
from django.urls import path
from .views import ShopUserLoginView, ShopUserLogoutView, ShopUserRegisterView, verify, edit
# ShopUserEditView,

app_name = 'authapp'

urlpatterns = [
    # path('login/', login, name='login'),
    path('login/', ShopUserLoginView.as_view(), name='login'),
    path('logout/', ShopUserLogoutView.as_view(), name='logout'),
    # path('logout/', logout, name='logout'),
    path('edit/', edit, name='edit'),
    # path('edit/', ShopUserEditView.as_view(), name='edit'),
    path('register/', ShopUserRegisterView.as_view(), name='register'),
    # path('register/', register, name='register'),
    path('verify/<str:email>/<str:activation_key>/', verify, name='verify'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index, contacts
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),

    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('order/', include('ordersapp.urls', namespace='order')),

    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
   import debug_toolbar

   urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/ordersapp/urls.py
from django.urls import path
from ordersapp.views import OrderList, OrderCreate, order_forming_complete, OrderRead, OrderUpdate, OrderDelete

app_name = 'ordersapp'

urlpatterns = [
    path('', OrderList.as_view(), name='orders_list'),
    path('forming/complete/<int:pk>/)', order_forming_complete, name='order_forming_complete'),
    path('create/', OrderCreate.as_view(), name='order_create'),
    path('read/<int:pk>/', OrderRead.as_view(), name='order_read'),
    path('update/<int:pk>/', OrderUpdate.as_view(), name='order_update'),
    path('delete/<int:pk>/', OrderDelete.as_view(), name='order_delete'),
]

geekshop/geekshop/views.py
import json
from django.shortcuts import render

from mainapp.models import Product

with open('geekshop/templates/geekshop/links_menu.json', 'r', encoding="utf-8") as content:
    links_menu = json.load(content)


def index(request):
    title = 'магазин'

    products = Product.objects.filter(is_deleted=False, category__is_deleted=False)[:3]


    context = {
        'title': title,
        'links_menu': links_menu,
        'products': products,
    }
    return render(request, 'geekshop/index.html', context=context)


def contacts(request):
    title = 'контакты'

    context = {
        'title': title,
        'links_menu': links_menu,
    }
    return render(request, 'geekshop/contact.html', context=context)

geekshop/geekshop/templates/geekshop/includes/inc_main_menu.html
<div class="{{ class }}">
    <div class="header clearfix">
        <a href="{% url 'index' %}" class="logo"></a>
        <ul class="menu">
            {% for item in links_menu %}
            <li><a href="{% url item.href %}" class="{% if item.href == active %}
                active
            {% endif %}">{{ item.name }}</a></li>
            {% endfor %}

            {% if user.is_superuser %}
            <li><a href="{% url 'admin_staff:users' %}">Админка</a></li>
            {% endif %}

            {% if user.is_authenticated %}
            <li style="margin-top: -8px;">
            <div class="dropdown">

               <a class="nav-link dropdown-toggle" href="#" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                   {{ user.first_name|default:'Пользователь' }}
                   <span class="caret"></span>
               </a>
               <ul class="dropdown-menu">
                   <li>
                       <a class="nav-link text-dark" href="{% url 'auth:edit' %}">
                           Профиль
                       </a>
                   </li>
                   <li>
                       <a class="nav-link text-dark" href="{% url 'ordersapp:orders_list' %}">
                           Заказы
                       </a>
                   </li>
               </ul>
            </div>
            </li>
            <li><a href="{% url 'auth:logout' %}">выйти</a></li>

            {% else %}
            <li><a href="{% url 'auth:login' %}">войти</a></li>
            <li><a href="{% url 'auth:register' %}">регистрация</a></li>
            {% endif %}
        </ul>
        <a href="#" class="search"></a>
        <div class="basket-summary">
        {% include 'basketapp/includes/inc_basket_summary.html' %}
        </div>
    </div>