geekshop/adminapp/urls.py
from django.urls import path

import adminapp.views as adminapp
from adminapp.views import UserListView, UserCreateView, UserUpdateView, UserDeleteView
from adminapp.views import ProductCategoryListView, ProductCategoryCreateView, ProductCategoryUpdateView, ProductCategoryDeleteView
from adminapp.views import ProductListView, ProductCreateView, ProductReadView, ProductUpdateView, ProductDeleteView

app_name = 'adminapp'

urlpatterns = [
    # path('users/create/', adminapp.user_create, name='user_create'),
    path('users/create/', UserCreateView.as_view(), name='user_create'),
    # path('users/read/', adminapp.users, name='users'),
    path('users/read/', UserListView.as_view(), name='users'),
    path('users/update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    # path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('users/delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
    # path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),

    path('categories/create/', ProductCategoryCreateView.as_view(), name='category_create'),
    # path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/read/', ProductCategoryListView.as_view(), name='categories'),
    # path('categories/read/', adminapp.categories, name='categories'),
    path('categories/update/<int:pk>/', ProductCategoryUpdateView.as_view(), name='category_update'),
    # path('categories/update/<int:pk>/', adminapp.category_update, name='category_update'),
    path('categories/delete/<int:pk>/', ProductCategoryDeleteView.as_view(), name='category_delete'),
    # path('categories/delete/<int:pk>/', adminapp.category_delete, name='category_delete'),

    path('products/create/category/<int:pk>/', ProductCreateView.as_view(), name='product_create'),
    path('products/read/category/<int:pk>/', ProductListView.as_view(), name='products'),
    path('products/read/<int:pk>/', ProductReadView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    # path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    # path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    # path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    # path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    # path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),
]

geekshop/authapp/urls.py
from django.urls import path
from .views import ShopUserLoginView, ShopUserLogoutView, ShopUserRegisterView, verify, edit
# ShopUserEditView,

app_name = 'authapp'

urlpatterns = [
    # path('login/', login, name='login'),
    path('login/', ShopUserLoginView.as_view(), name='login'),
    path('logout/', ShopUserLogoutView.as_view(), name='logout'),
    # path('logout/', logout, name='logout'),
    path('edit/', edit, name='edit'),
    # path('edit/', ShopUserEditView.as_view(), name='edit'),
    path('register/', ShopUserRegisterView.as_view(), name='register'),
    # path('register/', register, name='register'),
    path('verify/<str:email>/<str:activation_key>/', verify, name='verify'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index, contacts
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),

    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('order/', include('ordersapp.urls', namespace='order')),

    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
   import debug_toolbar

   urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/adminapp/models.py
from django.db import models

# Create your models here.

geekshop/adminapp/forms.py
from django import forms
from authapp.models import ShopUser
from authapp.forms import ShopUserEditForm
from mainapp.models import ProductCategory
from mainapp.models import Product


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = '__all__'


class ShopCategoryCreateForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = ''
            field.help_text = ''


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = ''
            field.help_text = ''


class ProductCategoryEditForm(forms.ModelForm):
    discount = forms.IntegerField(label='скидка', required=False, min_value=0, max_value=90, initial=0)

    class Meta:
        model = ProductCategory
        exclude = ()

geekshop/adminapp/views.py
from django.db import connection
from django.db.models import F
from django.db.models.signals import pre_save
from django.dispatch import receiver

from authapp.models import ShopUser
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from mainapp.models import Product, ProductCategory
from authapp.forms import ShopUserRegisterForm
from adminapp.forms import ShopUserAdminEditForm, ShopCategoryCreateForm, ProductEditForm, ProductCategoryEditForm


class UserListView(ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'
    context_object_name = 'objects'
    paginate_by = 3

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(UserListView, self).get_context_data()
        context['title'] = 'админка/пользователи'
        return context

    def get_queryset(self):
        return ShopUser.objects.all().order_by('-is_active', '-is_superuser', '-is_staff', 'username')


class UserCreateView(CreateView):
    model = ShopUser
    form_class = ShopUserRegisterForm
    template_name = 'adminapp/user_create.html'
    success_url = reverse_lazy('admin_staff:users')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(UserCreateView, self).get_context_data()
        context['title'] = 'пользователь/создать'
        return context


class UserUpdateView(UpdateView):
    model = ShopUser
    form_class = ShopUserAdminEditForm
    template_name = 'adminapp/user_update.html'
    success_url = reverse_lazy('admin_staff:users')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(UserUpdateView, self).get_context_data()
        context['title'] = 'пользователь/изменить'
        return context


class UserDeleteView(DeleteView):
    model = ShopUser
    template_name = 'adminapp/user_delete.html'
    success_url = reverse_lazy('admin_staff:users')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.is_deleted = True
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())


class ProductCategoryListView(ListView):
    model = ProductCategory
    template_name = 'adminapp/categories.html'
    context_object_name = 'objects'
    paginate_by = 3

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductCategoryListView, self).get_context_data()
        context['title'] = 'админка/категории'
        return context

    def get_queryset(self):
        return ProductCategory.objects.all().order_by('name')


class ProductCategoryCreateView(CreateView):
    model = ProductCategory
    form_class = ShopCategoryCreateForm
    template_name = 'adminapp/category_create.html'
    success_url = reverse_lazy('admin_staff:categories')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductCategoryCreateView, self).get_context_data()
        context['title'] = 'категория/создать'
        return context


class ProductCategoryUpdateView(UpdateView):
    model = ProductCategory
    form_class = ProductCategoryEditForm
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('admin_staff:categories')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductCategoryUpdateView, self).get_context_data()
        context['title'] = 'категория/изменить'
        return context

    def form_valid(self, form):
        if 'discount' in form.cleaned_data:
            discount = form.cleaned_data['discount']
            if discount:
                self.object.product_set.update(price=F('price') * (1 - discount / 100))
                db_profile_by_type(self.__class__, 'UPDATE', connection.queries)

        return super().form_valid(form)
    

class ProductCategoryDeleteView(DeleteView):
    model = ProductCategory
    template_name = 'adminapp/category_delete.html'
    success_url = reverse_lazy('admin_staff:categories')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.is_deleted = True
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())


class ProductListView(ListView):
    model = Product
    template_name = 'adminapp/products.html'
    context_object_name = 'objects'
    paginate_by = 3

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductListView, self).get_context_data()
        context['title'] = 'админка/продукты'
        context['category__pk'] = self.kwargs['pk']
        return context

    def get_queryset(self):
        return Product.objects.filter(category__pk=self.kwargs['pk']).order_by('name')


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductEditForm

    template_name = 'adminapp/product_create.html'

    def get_success_url(self):
        return reverse_lazy('admin_staff:products', args=[self.kwargs['pk']])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductCreateView, self).get_context_data()
        context['title'] = 'продукт/создать'
        context['category__pk'] = self.kwargs['pk']
        return context


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductEditForm
    template_name = 'adminapp/product_update.html'

    def get_success_url(self):
        return reverse_lazy('admin_staff:products', args=[self.object.category_id])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductUpdateView, self).get_context_data()
        context['title'] = 'продукт/изменить'
        return context


class ProductDeleteView(DeleteView):
    model = Product
    template_name = 'adminapp/product_delete.html'

    def get_success_url(self):
        return reverse_lazy('admin_staff:products', args=[self.object.category_id])

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.is_deleted = True
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())


class ProductReadView(DetailView):
    model = Product
    template_name = 'adminapp/product_read.html'


def db_profile_by_type(prefix, type, queries):
    update_queries = list(filter(lambda x: type in x['sql'], queries))
    print(f'db_profile {type} for {prefix}:')
    [print(query['sql']) for query in update_queries]


@receiver(pre_save, sender=ProductCategory)
def product_is_active_productcategory_save(sender, instance, **kwargs):
    if instance.pk:
        if instance.is_deleted:
            instance.product_set.update(is_deleted=True)
        else:
            instance.product_set.update(is_deleted=False)

        db_profile_by_type(sender, 'UPDATE', connection.queries)

geekshop/adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'geekshop/style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'adminapp/style.css' %}">
        <link rel="stylesheet" type="text/css"href='https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css'>
        <link rel="stylesheet" type="text/css" href="{% static 'geekshop/fonts/font-awesome/css/font-awesome.css' %}">

    {% block css %}
    {% endblock %}

    <script src='{% static "adminapp/script.js" %}'></script>

    {% block js %}
    {% endblock %}
</head>
<body id="body-pd">
<header class="header" id="header">
    <div class="header_toggle"><i class='bx bx-menu' id="header-toggle"></i></div>
    <div class="header_img"><img src="/media/{{ user.avatar|default:'avatar-default.png' }}" alt=""></div>
</header>
<div class="l-navbar" id="nav-bar">
    <nav class="nav">
        <div>
            <a href="{% url 'index' %}" class="nav_logo">
                <i class='bx bx-layer nav_logo-icon'></i>
                <span class="nav_logo-name">Admin`ka</span>
            </a>
            {% include 'adminapp/includes/inc_admin_menu.html' %}
        </div>
        <a href="{% url 'auth:logout' %}" class="nav_link"> <i class='bx bx-log-out nav_icon'></i> <span class="nav_name">Выход</span> </a>
    </nav>
</div>
<!--Container Main start-->
<div class="height-100 bg-light">
    {% block content %}
    {% endblock %}
</div>
<!--Container Main end-->
</body>
</html>

geekshop/adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Категории</h1>

        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo;</a>
                    <a href="?page={{ page_obj.previous_page_number }}"><</a>
                {% endif %}

                <span class="current">
                    Стр. {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">></a>
                    <a href="?page={{ page_obj.paginator.num_pages }}"> &raquo;</a>
                {% endif %}
            </span>
        </div>

        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Категории продуктов
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Имя</th>
                            <th>Редактировать</th>
                            <th>Удалить</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Имя</th>
                            <th>Редактировать</th>
                            <th>Удалить</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for category in objects %}
                            <tr {% if category.is_deleted %} style="opacity: 0.5;" {% endif %}>
                                <td><a href="{% url 'admin_staff:products' category.id %}" style="color: dodgerblue">{{ category.name }}</a></td>
                                <td>
                                    <a href="{% url 'admin_staff:category_update' pk=category.id %}">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                </td>

                                <td>
                                    <a {% if category.is_deleted %} class="invisible" {% endif %} href="{% url 'admin_staff:category_delete' pk=category.id %}">
                                        <i class="fa fa-times-circle"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'adminapp:category_create' %}">
                    <button class="btn btn-success">Создать категорию</button>
                </a>
            </div>
        </div>
    </div>
</main>
{% endblock %}

geekshop/adminapp/templates/adminapp/category_create.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="col-3 mx-auto">
    <form class="form-horizontal" action="{% url 'admin_staff:category_create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ category_form.as_p }}

        <input class="form-control" type="submit" value="Создать">
    </form>
    </div>

{% endblock %}

geekshop/adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
  <div class="user_delete">
    Уверены, что хотите удалить {{ category_to_delete.name }}?
    <form action="{% url 'admin_staff:category_delete' category_to_delete.pk %}"
          method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
      <a href="{% url 'admin_staff:categories' %}">
        Отмена
      </a>
    </button>
  </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/category_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="col-3 mx-auto">
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ category_form.as_p }}

        <input class="form-control" type="submit" value="Сохранить">
    </form>
    </div>

{% endblock %}

geekshop/adminapp/templates/adminapp/product_create.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="col-3 mx-auto">
    <form class="form-horizontal" action="{% url 'admin_staff:product_create' category__pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}

        <input class="form-control" type="submit" value="Создать">
    </form>
    </div>

{% endblock %}

geekshop/adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
  <div class="user_delete">
    Уверены, что хотите удалить {{ object.name }}?
    <form action="{% url 'admin_staff:product_delete' object.pk %}"
          method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
      <a href="{% url 'admin_staff:products' object.category.pk %}">
        Отмена
      </a>
    </button>
  </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_read.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}


{% block content %}

<div class="card" style="width: 18rem;">
  <img src="/media/{{ product.image|media_folder_products }}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{ product.name|title }}</h5>
    <p class="card-text">{{ product.description }}</p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">{{ product.price }} руб.</li>
    <li class="list-group-item">{{ product.quantity }} шт.</li>
  </ul>
  <!--div class="card-body">
    <a href="#" class="card-link">Card link</a>
    <a href="#" class="card-link">Another link</a>
  </div-->
</div>

{% endblock %}

geekshop/adminapp/templates/adminapp/product_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="col-3 mx-auto">
    <form class="form-horizontal" action="{% url 'admin_staff:product_update' product.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}

        <input class="form-control" type="submit" value="Сохранить">
    </form>
    </div>

{% endblock %}

geekshop/adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Продукты</h1>

        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo;</a>
                    <a href="?page={{ page_obj.previous_page_number }}"><</a>
                {% endif %}

                <span class="current">
                    Стр. {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">></a>
                    <a href="?page={{ page_obj.paginator.num_pages }}"> &raquo;</a>
                {% endif %}
            </span>
        </div>

        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                {{ category.name }}
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Название</th>
                            <th>Описание</th>
                            <th>Количество</th>
                            <th>Стоимость</th>
                            <th>Редактировать</th>
                            <th>Удалить</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Название</th>
                            <th>Описание</th>
                            <th>Количество</th>
                            <th>Стоимость</th>
                            <th>Редактировать</th>
                            <th>Удалить</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for product in objects %}
                            <tr {% if product.is_deleted %} style="opacity: 0.5;" {% endif %}>
                                <td><a href="{% url 'admin_staff:product_read' product.id %}" style="color: dodgerblue">{{ product.name }}</a></td>
                                <td>{{ product.short_desc }}</td>
                                <td>{{ product.quantity }}</td>
                                <td>{{ product.price }}</td>
                                <td>
                                    <a href="{% url 'admin_staff:product_update' pk=product.id %}">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                </td>
                                <td>
                                    <a {% if product.is_deleted %} class="invisible" {% endif %} href="{% url 'admin_staff:product_delete' pk=product.id %}">
                                        <i class="fa fa-times-circle"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'admin_staff:product_create' category__pk %}">
                    <button class="btn btn-success">Создать продукт</button>
                </a>
            </div>
        </div>
    </div>
</main>
{% endblock %}

geekshop/adminapp/templates/adminapp/user_create.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="col-3 mx-auto">
    <form class="form-horizontal" action="{% url 'admin_staff:user_create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}

        <input class="form-control" type="submit" value="Создать">
    </form>
    </div>

{% endblock %}

geekshop/adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
  <div class="user_delete">
    Уверены, что хотите удалить {{ object.username }}
    {% if object.first_name %}
      ({{ object.first_name|title }}</b>
      {% if object.last_name %}
        {{ object.last_name|title }}
      {% endif %})
    {% endif %}
    ?
    <form action="{% url 'admin_staff:user_delete' object.pk %}"
          method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
      <a href="{% url 'admin_staff:users' %}">
        Отмена
      </a>
    </button>
  </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/user_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="col-3 mx-auto">
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="form-control" type="submit" value="сохранить">
    </form>
    <button class="btn btn-round form-control last">
        <a href="{% url 'admin_staff:users' %}">
            к списку пользователей
        </a>
    </button>
</div>
{% endblock %}

geekshop/adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block js %}
{% endblock %}


{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Пользователи</h1>

        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo;</a>
                    <a href="?page={{ page_obj.previous_page_number }}"><</a>
                {% endif %}

                <span class="current">
                    Стр. {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">></a>
                    <a href="?page={{ page_obj.paginator.num_pages }}"> &raquo;</a>
                {% endif %}
            </span>
        </div>

        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Пользователи
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Имя пользователя</th>
                            <th>Имя</th>
                            <th>Фамилия</th>
                            <th>Адрес эл. почты</th>
                            <th>Персонал сайта</th>
                            <th>Активный</th>
                            <th>Вход</th>
                            <th>Удалить</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Имя пользователя</th>
                            <th>Имя</th>
                            <th>Фамилия</th>
                            <th>Адрес эл. почты</th>
                            <th>Персонал сайта</th>
                            <th>Активный</th>
                            <th>Вход</th>
                            <th>Удалить</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for user in objects %}
                        <tr {% if user.is_deleted %} style="opacity: 0.5;" {% endif %}>
                            <td><a href="{% url 'admin_staff:user_update' user.id %}" style="color: dodgerblue">
                                {{ user.username }}</a></td>
                            <td>{{ user.first_name }}</td>
                            <td>{{ user.last_name }}</td>
                            <td>{{ user.email }}</td>
                            <td class="text-center">
                                {% if user.is_staff %}
                                <i class="fa fa-check-circle"></i>
                                {% else %}
                                <i class="fa fa-times-circle"></i>
                                {% endif %}
                            </td>
                            <td class="text-center">
                                {% if user.is_active %}
                                <i class="fa fa-check-circle"></i>
                                {% else %}
                                <i class="fa fa-times-circle"></i>
                                {% endif %}
                            </td>
                            <td>{{ user.last_login }}</td>
                            <td>
                                <a {% if user.is_deleted %} class="invisible" {% endif %}
                                   href="{% url 'admin_staff:user_delete' pk=user.id %}">
                                    <i class="fa fa-times-circle"></i>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'adminapp:user_create' %}">
                    <button class="btn btn-success">Создать пользователя</button>
                </a>
            </div>
        </div>
    </div>
</main>
{% endblock %}