geekshop/authapp/urls.py
from django.urls import path
from .views import ShopUserLoginView, ShopUserLogoutView, ShopUserRegisterView, verify, edit
# ShopUserEditView,

app_name = 'authapp'

urlpatterns = [
    # path('login/', login, name='login'),
    path('login/', ShopUserLoginView.as_view(), name='login'),
    path('logout/', ShopUserLogoutView.as_view(), name='logout'),
    # path('logout/', logout, name='logout'),
    path('edit/', edit, name='edit'),
    # path('edit/', ShopUserEditView.as_view(), name='edit'),
    path('register/', ShopUserRegisterView.as_view(), name='register'),
    # path('register/', register, name='register'),
    path('verify/<str:email>/<str:activation_key>/', verify, name='verify'),
]

geekshop/basketapp/urls.py
from django.urls import path
from .views import BasketListView

app_name = 'basketapp'

urlpatterns = [
    path('', BasketListView.as_view(), name='view'),
    path('add/<int:pk>/', BasketListView.basket_add, name='add'),
    path('remove/<int:pk>/', BasketListView.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', BasketListView.basket_edit, name='edit'),

]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index, contacts
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),

    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('order/', include('ordersapp.urls', namespace='order')),

    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
   import debug_toolbar

   urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path
from mainapp.views import ProductReadView, ProductsListView, products_ajax
from django.views.decorators.cache import cache_page

app_name = 'products'

urlpatterns = [
    path('', ProductsListView.as_view(), name='index'),
    path('category/<int:pk>/', ProductsListView.as_view(), name='category'),
    # path('category/<int:pk>/', products, name='category'),
    # path('category/<int:pk>/page/<int:page>/', products, name='page'),
    path('product/<int:pk>/', ProductReadView.as_view(), name='product'),
    # path('product/<int:pk>/', product, name='product'),
    path('category/<int:pk>/ajax/', cache_page(3600)(products_ajax)),
    # path('category/<int:pk>/page/<int:pk>/ajax/', cache_page(3600)(products_ajax)),
]

geekshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(
        verbose_name='имя',
        max_length=64,
        unique=True,
    )
    description = models.TextField(
        verbose_name='описание',
        blank=True,
    )

    сreated = models.DateTimeField(
        auto_now_add=True,
    )
    updated = models.DateTimeField(
        auto_now=True,
    )

    is_deleted = models.BooleanField(
        default=False,
    )

    def __str__(self):
        return self.name or f'Product Category #{self.pk}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    category = models.ForeignKey(
        ProductCategory,
        on_delete=models.CASCADE,
    )
    name = models.CharField(
        verbose_name='имя',
        max_length=64,
        unique=True,
    )
    image = models.ImageField(
        verbose_name='изображение',
        upload_to='product_images',
        blank=True,
    )
    short_desc = models.CharField(
        verbose_name='краткое описание',
        max_length=128,
        blank=True,
    )
    description = models.TextField(
        verbose_name='описание',
        blank=True,
    )
    price = models.DecimalField(
        verbose_name='цена',
        max_digits=8,
        decimal_places=2,
        default=0,
    )
    quantity = models.PositiveIntegerField(
        verbose_name='количество на складе',
        default=0,
    )

    created = models.DateTimeField(
        auto_now_add=True
    )
    updated = models.DateTimeField(
        auto_now=True
    )

    is_deleted = models.BooleanField(
        default=False,
    )

    def __str__(self):
        return self.name or f'Product #{self.pk}'

    @staticmethod
    def get_items():
        return Product.objects.filter(is_deleted=False).order_by('category', 'name')

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'

geekshop/mainapp/views.py
import json
import random

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from mainapp.models import ProductCategory, Product

from basketapp.models import Basket

from django.conf import settings
from django.core.cache import cache

from django.views.decorators.cache import cache_page

from django.template.loader import render_to_string
from django.http import JsonResponse


with open('geekshop/templates/geekshop/links_menu.json', 'r', encoding="utf-8") as content:
   links_menu = json.load(content)


def get_links_menu():
   if settings.LOW_CACHE:
       key = 'links_menu'
       links_menu = cache.get(key)
       if links_menu is None:
           links_menu = ProductCategory.objects.filter(is_deleted=False)
           cache.set(key, links_menu)
       return links_menu
   else:
       return ProductCategory.objects.filter(is_deleted=False)


def get_category(pk):
   if settings.LOW_CACHE:
       key = f'category_{pk}'
       category = cache.get(key)
       if category is None:
           category = get_object_or_404(ProductCategory, pk=pk)
           cache.set(key, category)
       return category
   else:
       return get_object_or_404(ProductCategory, pk=pk)


def get_products():
   if settings.LOW_CACHE:
       key = 'products'
       products = cache.get(key)
       if products is None:
           products = Product.objects.filter(is_deleted=False, \
                         category__is_deleted=False).select_related('category')
           cache.set(key, products)
       return products
   else:
       return Product.objects.filter(is_deleted=False, \
                         category__is_deleted=False).select_related('category')


def get_product(pk):
   if settings.LOW_CACHE:
       key = f'product_{pk}'
       product = cache.get(key)
       if product is None:
           product = get_object_or_404(Product, pk=pk)
           cache.set(key, product)
       return product
   else:
       return get_object_or_404(Product, pk=pk)


def get_products_ordered_by_price():
   if settings.LOW_CACHE:
       key = 'products_orederd_by_price'
       products = cache.get(key)
       if products is None:
           products = Product.objects.filter(is_deleted=False, \
                                  category__is_deleted=False).order_by('price')
           cache.set(key, products)
       return products
   else:
       return Product.objects.filter(is_deleted=False,\
                                 category__is_deleted=False).order_by('price')


def get_products_in_category_ordered_by_price(pk):
   if settings.LOW_CACHE:
       key = f'products_in_category_orederd_by_price_{pk}'
       products = cache.get(key)
       if products is None:
           products = Product.objects.filter(category__pk=pk, is_deleted=False,\
                              category__is_deleted=False).order_by('price')
           cache.set(key, products)
       return products
   else:
       return Product.objects.filter(category__pk=pk, is_deleted=False, \
                              category__is_deleted=False).order_by('price')




def get_links_menu():
    if settings.LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_deleted=False)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.filter(is_deleted=False)


def get_category(pk):
    if settings.LOW_CACHE:
        key = f'category_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, pk=pk)


def get_products():
    if settings.LOW_CACHE:
        key = 'products'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_deleted=False, category__is_deleted=False).select_related('category')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_deleted=False, category__is_deleted=False).select_related('category')


def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product_{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


def get_products_ordered_by_price():
    if settings.LOW_CACHE:
        key = 'products_orederd_by_price'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_deleted=False, category__is_deleted=False).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_deleted=False, category__is_deleted=False).order_by('price')


def get_products_in_category_ordered_by_price(pk):
    if settings.LOW_CACHE:
        key = f'products_in_category_orederd_by_price_{pk}'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(category__pk=pk, is_deleted=False, category__is_deleted=False).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(category__pk=pk, is_deleted=False, category__is_deleted=False).order_by('price')


def get_basket(user):
    if user.is_authenticated:
        basket = Basket.objects.filter(user=user)
        return basket
    else:
        return []


def get_hot_product():
    products = get_products()
    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_product = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)
    return same_product


class ProductsListView(ListView):
    Model = Product
    template_name = 'mainapp/products.html'
    context_object_name = 'products'
    paginate_by = 3

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductsListView, self).get_context_data()
        context['title'] = 'продукты'
        context['links_menu'] = links_menu
        context['basket'] = get_basket(self.request.user)
        context['hot_product'] = get_hot_product()
        context['same_products'] = get_same_products(context['hot_product'])
        context['product_categories'] = ProductCategory.objects.all()
        if 'pk' in self.kwargs and self.kwargs['pk']:
            context['category'] = get_category(self.kwargs['pk'])
        return context

    def get_queryset(self):
        if 'pk' in self.kwargs:
            if self.kwargs['pk']:
                return get_products_in_category_ordered_by_price(self.kwargs['pk'])

            else:
                return get_products_ordered_by_price()
        else:
            return get_products_ordered_by_price()

# Product.objects.all()


class ProductReadView(DetailView):
    Model = Product
    template_name = 'mainapp/product.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductReadView, self).get_context_data()
        context['title'] = 'продукты'
        context['links_menu'] = links_menu
        return context
    
    def get_object(self):
        return get_product(pk=self.kwargs['pk'])


def products_ajax(request, pk=None, page=1):
    if request.is_ajax():
        if pk is not None:
            if pk == 0:
                category = {
                   'pk': 0,
                   'name': 'все'
                }
                products = get_products_ordered_by_price()
            else:
                category = get_category(pk)
                products = get_products_in_category_ordered_by_price(pk)

            paginator = Paginator(products, 2)
            try:
                products_paginator = paginator.page(page)
            except PageNotAnInteger:
                products_paginator = paginator.page(1)
            except EmptyPage:
                products_paginator = paginator.page(paginator.num_pages)

            context = {
               'category': category,
               'products': products
            }

            result = render_to_string(
               'mainapp/includes/inc_products_list_content.html',
               context=context,
               request=request)

            # context2 = {
            #    'product_categories': product_categories,
            # }
            #
            # result2 = render_to_string(
            #    'mainapp/includes/inc_product_categories.html',
            #    context=context2,
            #    request=request)

            return JsonResponse({'result': result})



    def get_object(self):
        return get_product(pk=self.kwargs['pk'])

geekshop/mainapp/templates/mainapp/product.html
{% extends 'geekshop/base.html' %}
{% load static %}
{% load my_tags %}


{% block content %}
{% include 'geekshop/includes/inc_main_menu.html' with active="products:index" class="hero-white" %}
</div>
<div class="details">


    <div class="details-products">
        <div class="details-slider">
            <div class="slider-product">
                <img src="/media/{{ product.image|media_folder_products }}">
            </div>
            <div class="slider-control">
                <div class="block">
                    <a href="#"><img src="/media/{{ product.image|media_folder_products }}" alt="" style="width:50px;">
                        <div class="text"></div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="/media/{{ product.image|media_folder_products }}" alt="" style="width:50px;">
                        <div class="text"></div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="/media/{{ product.image|media_folder_products }}" alt="" style="width:50px;">
                        <div class="text">{{basket}}</div>
                    </a>
                </div>
            </div>
        </div>

        <div class="description">
            <h3 class="big-bold">{{ product|title }}</h3>
            <h3 class="red">{{ product.short_desc }}</h3>
            <p class="price"> {{ product.price|floatformat:0 }} <span>руб</span></p>
            <a href="{% url 'basket:add' product.pk %}" class="red-button">
                заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
            </a>
            <div class="description-text">
                {{ product.description }}
            </div>
        </div>
    </div>
</div>

{% endblock %}

geekshop/mainapp/templates/mainapp/products.html
{% extends 'geekshop/base.html' %}
{% load static %}
{% load my_tags %}



{% block content %}
    {% include 'geekshop/includes/inc_main_menu.html' with active="products:index" class="hero-white" %}
</div>
<div class="product_categories">
{% include 'mainapp/includes/inc_product_categories.html' %}
</div>
<div class="details">

    <div class="details-products">
        <div class="details-slider">
            <div class="slider-product">
                <img src="/media/{{ hot_product.image|media_folder_products }}">
            </div>
            <div class="slider-control">
                <div class="block">
                    <a href="#"><img src="/media/{{ hot_product.image|media_folder_products }}" alt=""
                                     style="width:50px;">
                        <div class="text"></div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="/media/{{ hot_product.image|media_folder_products }}" alt=""
                                     style="width:50px;">
                        <div class="text"></div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="/media/{{ hot_product.image|media_folder_products }}" alt=""
                                     style="width:50px;">
                        <div class="text"></div>
                    </a>
                </div>
            </div>
        </div>

        <div class="description">
            <h3 class="big-bold">{{ hot_product|title }}</h3>
            <h3 class="red">{{ hot_product.short_desc }}</h3>
            <p class="price"> {{ hot_product.price|floatformat:0 }} <span>руб</span></p>
            <a href="{% url 'products:product' hot_product.pk %}" class="red-button">
                заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
            </a>
            <div class="description-text">
                {{ hot_product.description }}
            </div>
        </div>
    </div>
    {% include 'mainapp/includes/inc_products_list_content.html' %}
        <!--        <div class="title pagination">-->
        <!--            {% if page_obj.has_previous %}-->
        <!--            <a href="{{page_obj.previous_page_number}}">-->
        <!--                <-->
        <!--            </a>-->
        <!--            {% endif %}-->
        <!--            <span class="current">-->
        <!--                страница {{ product_items.number }} из {{ product_items.paginator.num_pages }}-->
        <!--            </span>-->
        <!--            {% if product_items.has_next %}-->
        <!--            <a href="{% url 'products:page' category.pk product_items.next_page_number %}">-->
        <!--                >-->
        <!--            </a>-->
        <!--            {% endif %}-->
        <!--        </div>-->








        <div class="related">
            <div class="title clearfix">
                <h2>Похожие продукты</h2>
                <!--a class="explore" href="#">показать все <img src="{% static 'geekshop/img/arrow.png' %}" alt=""></a-->
            </div>
            <div class="related-products clearfix">
                {% for item in same_products %}
                <div class="block">
                    <a href="#"><img src="/media/{{item.image}}" alt="">
                        <div class="text">
                            <img src="{% static 'geekshop/img/icon-hover.png' %}" alt="img">
                            <h4>{{ item.name }}</h4>
                            <p>{{ item.short_desc }}</p>
                        </div>
                    </a>
                </div>
                {% endfor %}

            </div>
        </div>
    </div>

    <div class="clr"></div>

</div>

{% endblock %}